### ISSUE TITLE
Implenation

### ISSUE THREAD

**Issue by akinamon** [oreliyahu1/ClassBoostDownloader#1]
Hi @oreliyahu1 
Can you assist me how to implement this?
I have user and password in Classboost

**Comment by oreliyahu1** [comment]
Hi @akinamon,
you should download any c# compiler (or IDE like Microsoft visual studio) and compile&run it by yourself

**Comment by akinamon** [comment]
Thanks
Which file do i need to run?

**Comment by oreliyahu1** [comment]
open the project file (ClassBoostDownloader.csproj)
this file contains the list of the files included in a project
