### ISSUE TITLE
Assistance with implementation

### ISSUE THREAD

**Issue by akinamon** [oreliyahu1/ClassBoostDownloader#2]
Hi @oreliyahu1 
I really appreciate if you assist me with implement this (via teamviewer or anydesk)
I'

**Comment by oreliyahu1** [comment]
the executable file has been committed...
you can run it without compiling the project

https://github.com/oreliyahu1/ClassBoostDownloader/commit/4ca0371c7f871774cec11bb8fc492039ff57772f

**Comment by akinamon** [comment]
Thanks
It works but how do I download the videos:
[image: image.png]

[image: image.png]

‫בתאריך יום ב׳, 25 במאי 2020 ב-17:43 מאת ‪Or Eliyahu‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by akinamon** [comment]
never mind I think I got it

‫בתאריך יום ב׳, 25 במאי 2020 ב-17:43 מאת ‪Or Eliyahu‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by akinamon** [comment]
by the way, is there a way to download multiple videos simultaneously?


‫בתאריך יום ב׳, 25 במאי 2020 ב-17:43 מאת ‪Or Eliyahu‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by oreliyahu1** [comment]
you can open the app multiple times
